name = "SchrodingerSolver"
uuid = "1da5ace5-5bdf-4bf3-9d71-834c5f86419d"
authors = ["walexaindre <walexaindre@hotmail.com\n> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
